

name: Build and Test  

on:  
  push:  
    branches: [ "main" ]  
  pull_request:  
    branches: [ "main" ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v4  
    - name: Use Node 20  
      uses: actions/setup-node@v4  
      with:  
        node-version: 20  
        cache: 'npm'  
    - name: Install dependencies  
      run: npm install
    - name: Replace the backend endpoint
      run: echo "export const settings = {host:\"http://localhost:3030\"}" > src/config.js  
    - name: Build frontend  
      run: npm run start_fe &  
    - name: Build backend  
      run: npm run start_be &  
    - run: npx playwright install  
    - name: Run tests  
      run: npm test  

  deploy-be:  
    needs: build  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout the repository  
        uses: actions/checkout@v3  
      - name: Deploy BackEnd  
        uses: JorgeLNJunior/render-deploy@v1.4.4  
        with:  
          service_id: ${{ secrets.HOOK_BE }}  
          api_key: ${{ secrets.APP_KYE }}  # Проверете името на секрет, за да е коректно  
          wait_deploy: true  

  deploy-fe:  
    needs: build  # Поправете 'build_test' на 'build'  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout the repository  
        uses: actions/checkout@v3  
      - name: Deploy FrontEnd  
        uses: JorgeLNJunior/render-deploy@v1.4.4  
        with:  
          service_id: ${{ secrets.MY_HOOK_FE }}  
          api_key: ${{ secrets.APP_KYE }}  # Проверете името на секрет, за да е коректно  
          wait_deploy: true
