

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: install
      run: npm install
    - name: build frond end 
      run: npm run start_fe &
    - name: build becken end
      run: npm run start_be &
    - run: npx playwright install
    - name: run test
      run: npm test
